### ISSUE TITLE
Maybe PyPy?

### ISSUE THREAD

**Issue by FKD13** [12urenloop/Ronny-the-station-chef#9]
We had some concerns speed wise about the FastAPI app. Scaling to multiple workers already helped a lot. Might be worh looking into PyPy to see if this gives us any significant speedup.

**Comment by redfast00** [comment]
Last time, we also saw that FastAPI (ironically) also wasn't really all that fast, compared to for example Flask. Maybe it makes sense to profile the web server, to see where the time is being spent (ideally we stay within FastAPI and just tweak some configuration, without having to rewrite this from scratch).

Aside: Maybe the 'Fast' part of 'FastAPI4 is about development speed, not about runtime speed?

**Comment by FKD13** [comment]
I tested this locally. Results ended up being slower than normal python. Next to having to jump trough some hoops to get it to work in the first place :D So discarding this idea.
